name: Convert Clash rules to QuantumultX

on:
  workflow_dispatch:       # 手动运行
  schedule:
    - cron: "0 0 * * *"    # 每天 00:00 自动运行

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python dependencies
        run: pip install pyyaml requests

      - name: Run convert script
        run: python convert.py
        
      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update QX list files"
          file_pattern: "*.list README.md"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
